clear
clc
%uxx+uyy =0enR u(0,y)=0, u(π,y)=0, 0≤y≤π u(x,0) = 4senh(π)sen(x), u(x,π) = 0, 0 ≤ x ≤ π.
funseg=@(x,y)(0);
funa=@(x,y)(0);
funb=@(x,y)(4*sinh(pi)*sin(x));
func=@(x,y)(0);
fund=@(x,y)(0);
Nx=10;
Ny=15;
A=0;
B=pi;
C=0;
D=pi;
tol=10^(-10);
maxit=9999;
w=1;
tic
[x,y,U,iter,salida]=GaussSeidelEDP(funseg,funa,funb,func,fund,A,B,C,D,tol,maxit,Nx,Ny);
tgaussseidel=toc
itergaussseidel=iter
dibujapoisson(x,y,U,1)
figure(3)
ezmesh('4.*sinh(pi-y).*sin(x)',[0 pi 0 pi])

%b)
Nx=10;
Ny=10;
A=0;
B=pi;
C=0;
D=pi;
tol=10^(-10);
maxit=9999;
w=2/(1+sin(pi/(10+1)));
tic
[x,y,U,iter,salida]=poisson_problem(funseg,funa,funb,func,fund,A,B,C,D,tol,maxit,Nx,Ny,w);
tomegaoptimo=toc
iteromegaoptimo=iter
dibujapoisson(x,y,U,4)
